import { chmodSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { PATHS } from "../paths.js";
import { getGhToken } from "./gh-token.js";

/**
 * Path to the git credential helper script written by the daemon.
 * This script echoes the GH_TOKEN env var as git credentials,
 * enabling HTTPS git operations in non-interactive environments (systemd, CI).
 */
const CREDENTIAL_HELPER_PATH = join(PATHS.home, "git-credential-helper.sh");

/**
 * Ensure the git credential helper script exists on disk.
 * Idempotent — safe to call multiple times.
 */
function ensureCredentialHelper(): void {
	if (existsSync(CREDENTIAL_HELPER_PATH)) return;

	const dir = PATHS.home;
	if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

	// The helper is invoked by git credential fill.
	// It reads stdin for the protocol/host, then outputs credentials.
	const script = `#!/bin/sh
# IO daemon git credential helper — provides GH_TOKEN for HTTPS GitHub operations
# This file is auto-generated by the IO daemon.
while read line; do
  case "$line" in "") break ;; esac
done
echo "protocol=https"
echo "host=github.com"
echo "username=x-access-token"
echo "password=$GH_TOKEN"
`;

	writeFileSync(CREDENTIAL_HELPER_PATH, script, { mode: 0o755 });
	try {
		chmodSync(CREDENTIAL_HELPER_PATH, 0o755);
	} catch {
		// chmod may fail on Windows, non-critical
	}
}

/**
 * Build a shell environment with GitHub/git credentials injected.
 * Used by shell_exec tools to enable non-interactive git push and gh CLI operations.
 */
export function buildShellEnv(): Record<string, string | undefined> {
	// Ensure HOME is present for subprocesses (some environments may unset it for spawned agents)
	const home = process.env.HOME ?? PATHS.home;
	const env: Record<string, string | undefined> = {
		...process.env,
		HOME: home,
		GH_PROMPT_DISABLED: "1",
		GIT_TERMINAL_PROMPT: "0",
	};

	const ghToken = getGhToken();
	if (ghToken) {
		env.GH_TOKEN = ghToken;
		env.GITHUB_TOKEN = ghToken;

		// Configure git to use our credential helper for HTTPS auth
		ensureCredentialHelper();
		env.GIT_CONFIG_COUNT = "1";
		env.GIT_CONFIG_KEY_0 = "credential.helper";
		env.GIT_CONFIG_VALUE_0 = CREDENTIAL_HELPER_PATH;
	}

	return env;
}
