import { execSync } from 'node:child_process';
import { createChildLogger } from '../../logging/logger.js';
import type { Instance } from './instance.js';
import { transitionInstance } from './instance.js';

const logger = () => createChildLogger('pr');

export interface PrResult {
	url: string;
	number: number;
}

/**
 * Create a pull request from the instance's worktree branch.
 * Commits any uncommitted changes, pushes the branch, then creates a PR.
 */
export async function createPullRequest(params: {
	instance: Instance;
	title: string;
	squadName: string;
}): Promise<PrResult | null> {
	const log = logger();
	const { instance, title, squadName } = params;

	if (!instance.worktree || !instance.branch) {
		log.warn({ instanceId: instance.id }, 'No worktree/branch, skipping PR creation');
		await transitionInstance(instance.id, 'complete');
		return null;
	}

	const cwd = instance.worktree.path;

	try {
		// Check if there are changes to commit
		const status = execSync('git status --porcelain', { cwd, encoding: 'utf-8' }).trim();
		if (!status) {
			log.info({ instanceId: instance.id }, 'No changes to commit');
			await transitionInstance(instance.id, 'complete');
			return null;
		}

		// Stage and commit all changes
		execSync('git add -A', { cwd, stdio: 'pipe' });

		const commitMessage = buildCommitMessage(title, instance, squadName);
		execSync(`git commit -m "${escapeShell(commitMessage)}"`, { cwd, stdio: 'pipe' });

		// Push the branch
		execSync(`git push -u origin "${instance.branch}"`, { cwd, stdio: 'pipe' });

		// Create the PR using gh CLI
		const prBody = buildPrBody(instance, squadName);
		const prOutput = execSync(
			`gh pr create --title "${escapeShell(title)}" --body "${escapeShell(prBody)}" --head "${instance.branch}"`,
			{ cwd, encoding: 'utf-8', stdio: 'pipe' },
		).trim();

		// Parse the PR URL to get the number
		const prUrl = prOutput;
		const prNumber = Number.parseInt(prUrl.split('/').pop() ?? '0', 10);

		await transitionInstance(instance.id, 'complete');
		log.info({ instanceId: instance.id, prUrl, prNumber }, 'PR created');

		return { url: prUrl, number: prNumber };
	} catch (err) {
		log.error({ err, instanceId: instance.id }, 'Failed to create PR');
		await transitionInstance(instance.id, 'failed');
		return null;
	}
}

function buildCommitMessage(title: string, instance: Instance, squadName: string): string {
	const lines = [`feat: ${title}`, '', `Squad: ${squadName}`, `Instance: ${instance.id}`];

	if (instance.issueRef) {
		lines.push(`Closes ${instance.issueRef}`);
	}

	const completedTasks = instance.tasks.filter((t) => t.status === 'done');
	if (completedTasks.length > 0) {
		lines.push('', 'Tasks completed:');
		for (const task of completedTasks) {
			lines.push(`- ${task.description} (${task.assignedTo})`);
		}
	}

	return lines.join('\n');
}

function buildPrBody(instance: Instance, squadName: string): string {
	const sections: string[] = [];

	sections.push(`## 🤖 Generated by IO Squad: ${squadName}`);
	sections.push('');

	if (instance.issueRef) {
		sections.push(`Closes ${instance.issueRef}`);
		sections.push('');
	}

	// Tasks section
	sections.push('### Tasks Completed');
	for (const task of instance.tasks) {
		const icon = task.status === 'done' ? '✅' : task.status === 'failed' ? '❌' : '⏳';
		sections.push(`${icon} ${task.description} — *${task.assignedTo}*`);
	}

	// Meeting highlights (last few entries)
	if (instance.meetingLog.length > 0) {
		sections.push('');
		sections.push('<details><summary>Meeting Discussion</summary>');
		sections.push('');
		const recentLog = instance.meetingLog.slice(-10);
		for (const entry of recentLog) {
			sections.push(`> ${entry.slice(0, 200)}`);
			sections.push('');
		}
		sections.push('</details>');
	}

	return sections.join('\n');
}

function escapeShell(str: string): string {
	return str.replace(/"/g, '\\"').replace(/\n/g, '\\n');
}
